name: Build and Deploy
on:
  push:
    branches: [ gh-pages ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-node@v1
          with:
              node-version: 14
        - uses: actions/checkout@v1
        - run: sh ./deploy-script.sh
          env:
              DEPLOY_TOKEN: ${{ secrets.ACCESS_TOKEN }}
